// DONNÉES DE DÉMONSTRATION - à supprimer quand les clés API seront configurées

export const DEMO_USER = {
  id: 'demo-user-1',
  first_name: 'Jean',
  last_name: 'Dupont',
  email: 'jean.dupont@email.fr',
  phone: '06 12 34 56 78',
  role: 'client' as const,
};

export const DEMO_LIVRIZEUR_USER = {
  id: 'demo-livrizeur-1',
  first_name: 'Marc',
  last_name: 'Martin',
  email: 'marc.martin@email.fr',
  phone: '07 98 76 54 32',
  role: 'livrizeur' as const,
};

export const DEMO_LIVRIZEUR_PROFILE = {
  id: 'demo-livrizeur-profile-1',
  user_id: 'demo-livrizeur-1',
  vehicle_type: '11m3' as const,
  radius_km: 30,
  average_rating: 4.8,
  total_ratings: 47,
  status: 'active' as const,
  siret: '12345678900012',
  address: '12 Rue de la Paix, Paris 75001',
  latitude: 48.8697,
  longitude: 2.3309,
};

export const DEMO_COURSES = [
  {
    id: 'course-1',
    status: 'en_livraison' as const,
    pickup_address: '15 Rue de Rivoli, Paris 75001',
    dropoff_address: '42 Avenue des Champs-Élysées, Paris 75008',
    vehicle_type: '11m3' as const,
    scheduled_date: new Date().toISOString().split('T')[0],
    scheduled_slot: '09:00 - 12:00',
    price_total: 189,
    livrizeur_amount: 132,
    movers: 2 as const,
    manutention: 'prolongee' as const,
    route_minutes: 25,
    items_description: 'Canapé 3 places, table basse, 8 cartons',
    pickup_access: 'etages_sans_ascenseur' as const,
    pickup_floors: 2,
    dropoff_access: 'etages_avec_ascenseur' as const,
    dropoff_floors: 4,
    client_id: 'demo-user-1',
    livrizeur_id: 'demo-livrizeur-profile-1',
    livrizeur: {
      id: 'demo-livrizeur-profile-1',
      vehicle_type: '11m3' as const,
      average_rating: 4.8,
      total_ratings: 47,
      user: { first_name: 'Marc', last_name: 'Martin', phone: '07 98 76 54 32' },
    },
    tip_amount: 0,
    payment_status: 'captured' as const,
    price_per_min: 0,
    commission_amount: 0,
    helper_amount: 0,
    pickup_lat: 48.8603,
    pickup_lng: 2.3477,
    dropoff_lat: 48.8698,
    dropoff_lng: 2.3078,
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'course-2',
    status: 'terminee' as const,
    pickup_address: '8 Place de la Bastille, Paris 75011',
    dropoff_address: '120 Boulevard Haussmann, Paris 75008',
    vehicle_type: '6m3' as const,
    scheduled_date: new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0],
    scheduled_slot: '14:00 - 17:00',
    price_total: 129,
    livrizeur_amount: 90,
    movers: 1 as const,
    manutention: 'express' as const,
    route_minutes: 18,
    items_description: '4 cartons, valises, vélo pliant',
    pickup_access: 'pied_camion' as const,
    pickup_floors: 0,
    dropoff_access: 'pied_camion' as const,
    dropoff_floors: 0,
    client_id: 'demo-user-1',
    livrizeur_id: 'demo-livrizeur-profile-1',
    livrizeur: {
      id: 'demo-livrizeur-profile-1',
      vehicle_type: '6m3' as const,
      average_rating: 4.9,
      total_ratings: 32,
      user: { first_name: 'Sophie', last_name: 'Bernard', phone: '06 45 67 89 01' },
    },
    tip_amount: 10,
    payment_status: 'captured' as const,
    price_per_min: 0,
    commission_amount: 0,
    helper_amount: 0,
    pickup_lat: 48.8533,
    pickup_lng: 2.3692,
    dropoff_lat: 48.8751,
    dropoff_lng: 2.3264,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    completed_at: new Date(Date.now() - 86400000 * 3 + 7200000).toISOString(),
  },
  {
    id: 'course-3',
    status: 'terminee' as const,
    pickup_address: '5 Rue du Faubourg Saint-Antoine, Paris 75011',
    dropoff_address: '88 Avenue de la République, Paris 75011',
    vehicle_type: '20m3' as const,
    scheduled_date: new Date(Date.now() - 86400000 * 10).toISOString().split('T')[0],
    scheduled_slot: '08:00 - 12:00',
    price_total: 320,
    livrizeur_amount: 224,
    movers: 2 as const,
    manutention: 'prolongee_plus' as const,
    route_minutes: 12,
    items_description: 'Déménagement complet 3 pièces : meubles, électroménager, 20 cartons',
    pickup_access: 'etages_avec_ascenseur' as const,
    pickup_floors: 3,
    dropoff_access: 'etages_sans_ascenseur' as const,
    dropoff_floors: 2,
    client_id: 'demo-user-1',
    livrizeur_id: 'demo-livrizeur-profile-1',
    livrizeur: {
      id: 'demo-livrizeur-profile-1',
      vehicle_type: '20m3' as const,
      average_rating: 4.7,
      total_ratings: 89,
      user: { first_name: 'Thomas', last_name: 'Leclerc', phone: '06 78 90 12 34' },
    },
    tip_amount: 20,
    payment_status: 'captured' as const,
    price_per_min: 0,
    commission_amount: 0,
    helper_amount: 0,
    pickup_lat: 48.8532,
    pickup_lng: 2.3712,
    dropoff_lat: 48.8654,
    dropoff_lng: 2.3707,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    completed_at: new Date(Date.now() - 86400000 * 10 + 14400000).toISOString(),
  },
];

export const DEMO_AVAILABLE_MISSIONS = [
  {
    id: 'mission-1',
    status: 'en_attente' as const,
    pickup_address: '3 Rue de la Pompe, Paris 75016',
    dropoff_address: '55 Avenue Victor Hugo, Paris 75016',
    vehicle_type: '11m3' as const,
    scheduled_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    scheduled_slot: '09:00 - 12:00',
    price_total: 175,
    livrizeur_amount: 122,
    movers: 2 as const,
    manutention: 'prolongee' as const,
    route_minutes: 15,
    items_description: 'Armoire 2 portes, lit double, 6 cartons livres',
    pickup_access: 'etages_sans_ascenseur' as const,
    pickup_floors: 1,
    dropoff_access: 'etages_avec_ascenseur' as const,
    dropoff_floors: 3,
    client_id: 'demo-user-1',
    livrizeur_id: null,
    tip_amount: 0,
    payment_status: 'pending' as const,
    price_per_min: 0,
    commission_amount: 0,
    helper_amount: 0,
    pickup_lat: 48.8641,
    pickup_lng: 2.2788,
    dropoff_lat: 48.8697,
    dropoff_lng: 2.2886,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-2',
    status: 'en_attente' as const,
    pickup_address: '22 Rue Oberkampf, Paris 75011',
    dropoff_address: '14 Boulevard Beaumarchais, Paris 75011',
    vehicle_type: '11m3' as const,
    scheduled_date: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    scheduled_slot: '14:00 - 17:00',
    price_total: 145,
    livrizeur_amount: 101,
    movers: 1 as const,
    manutention: 'express' as const,
    route_minutes: 12,
    items_description: "Canapé d'angle, table à manger + 6 chaises, 4 cartons",
    pickup_access: 'pied_camion' as const,
    pickup_floors: 0,
    dropoff_access: 'pied_camion' as const,
    dropoff_floors: 0,
    client_id: 'demo-user-2',
    livrizeur_id: null,
    tip_amount: 0,
    payment_status: 'pending' as const,
    price_per_min: 0,
    commission_amount: 0,
    helper_amount: 0,
    pickup_lat: 48.8651,
    pickup_lng: 2.3714,
    dropoff_lat: 48.8583,
    dropoff_lng: 2.3656,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-3',
    status: 'en_attente' as const,
    pickup_address: '1 Rue de Bretagne, Paris 75003',
    dropoff_address: '78 Rue du Temple, Paris 75003',
    vehicle_type: '11m3' as const,
    scheduled_date: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
    scheduled_slot: '08:00 - 12:00',
    price_total: 210,
    livrizeur_amount: 147,
    movers: 2 as const,
    manutention: 'prolongee_plus' as const,
    route_minutes: 8,
    items_description: 'Studio complet : canapé, bureau, étagères, 10 cartons',
    pickup_access: 'etages_avec_ascenseur' as const,
    pickup_floors: 5,
    dropoff_access: 'etages_avec_ascenseur' as const,
    dropoff_floors: 2,
    client_id: 'demo-user-3',
    livrizeur_id: null,
    tip_amount: 0,
    payment_status: 'pending' as const,
    price_per_min: 0,
    commission_amount: 0,
    helper_amount: 0,
    pickup_lat: 48.8627,
    pickup_lng: 2.3594,
    dropoff_lat: 48.8613,
    dropoff_lng: 2.3521,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_MY_MISSIONS = [
  {
    id: 'my-mission-1',
    status: 'acceptee' as const,
    pickup_address: '9 Rue Lepic, Paris 75018',
    dropoff_address: '32 Rue des Abbesses, Paris 75018',
    vehicle_type: '11m3' as const,
    scheduled_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    scheduled_slot: '10:00 - 13:00',
    price_total: 195,
    livrizeur_amount: 136,
    movers: 2 as const,
    manutention: 'prolongee' as const,
    route_minutes: 10,
    items_description: 'Bibliothèque, 2 fauteuils, 8 cartons',
    pickup_access: 'etages_sans_ascenseur' as const,
    pickup_floors: 2,
    dropoff_access: 'etages_sans_ascenseur' as const,
    dropoff_floors: 1,
    client_id: 'demo-client-2',
    livrizeur_id: 'demo-livrizeur-profile-1',
    client: { first_name: 'Alice', last_name: 'Moreau', phone: '06 23 45 67 89' },
    tip_amount: 0,
    payment_status: 'captured' as const,
    price_per_min: 0,
    commission_amount: 0,
    helper_amount: 0,
    pickup_lat: 48.8867,
    pickup_lng: 2.3369,
    dropoff_lat: 48.8845,
    dropoff_lng: 2.3387,
    created_at: new Date().toISOString(),
  },
];
